// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title MockZKVerifier
 * @notice Testnet mock — uses ECDSA signature verification instead of real ZK proofs.
 *         In production, replace with Groth16/PLONK verifier generated by EZKL.
 *
 *         The "proof" on testnet is simply:
 *         keccak256(abi.encode(newValue, policyId, timestamp)) signed by an authorized prover.
 */
contract MockZKVerifier is Ownable {
    // Authorized proof signers (off-chain agents)
    mapping(address => bool) public authorizedProvers;

    bool public mockMode; // true = testnet (skip real proof), false = mainnet

    event ProverAdded(address indexed prover);
    event ProverRemoved(address indexed prover);

    error UnauthorizedProver();
    error InvalidSignature();

    constructor(bool _mockMode) Ownable(msg.sender) {
        mockMode = _mockMode;
    }

    function addProver(address prover) external onlyOwner {
        authorizedProvers[prover] = true;
        emit ProverAdded(prover);
    }

    function removeProver(address prover) external onlyOwner {
        authorizedProvers[prover] = false;
        emit ProverRemoved(prover);
    }

    /**
     * @notice Verify a ZK proof.
     * @param proof    In mock mode: abi.encode(v, r, s) ECDSA signature.
     *                 In prod mode: actual Groth16 proof bytes.
     * @param input    abi.encode(newValue, policyId, timestamp)
     */
    function verify(
        bytes calldata proof,
        bytes calldata input
    ) external view returns (bool) {
        if (mockMode) {
            return _verifySignature(proof, input);
        }
        // TODO: Replace with real Groth16 verifier call
        // return IGroth16Verifier(verifierAddress).verifyProof(proof, input);
        return _verifySignature(proof, input);
    }

    function _verifySignature(
        bytes calldata proof,
        bytes calldata input
    ) internal view returns (bool) {
        if (proof.length == 0) return false;

        bytes32 messageHash = keccak256(input);
        bytes32 ethHash = keccak256(
            abi.encodePacked("\x19Ethereum Signed Message:\n32", messageHash)
        );

        (bytes32 r, bytes32 s, uint8 v) = _splitSignature(proof);
        address recovered = ecrecover(ethHash, v, r, s);

        if (!authorizedProvers[recovered]) return false;
        return true;
    }

    function _splitSignature(bytes calldata sig)
        internal pure returns (bytes32 r, bytes32 s, uint8 v)
    {
        require(sig.length == 65, "Invalid sig length");
        assembly {
            r := calldataload(sig.offset)
            s := calldataload(add(sig.offset, 32))
            v := byte(0, calldataload(add(sig.offset, 64)))
        }
    }

    function setMockMode(bool _mockMode) external onlyOwner {
        mockMode = _mockMode;
    }
}
